screen scr_kishi():
    label _("Nobusuke Kishi")
    add "images/cdx/peo/001_kishi.png"
    text _("""Born: 13/11/1896""") justify True
    text _("""Died: 07/08/1987\n""") justify True
    
    text _("""Also known as 'Monster of the Showa Era', nickname coined by the journalist Takao Iwami, Nobusuke Kishi is one of the most influential and controversial figures of immediate post-war Japan. A career bureaucrat and graduate of the Imperial University of Tokyo, it's during his attending the institution that he first came in contact with Japanese ethnonationalism.""") justify True
    text _("""His adherence to this ideology was exemplified in the handling of his first prominent role in the Japanese imperial apparatus, as Vice Minister of Industrial Development for the puppet state of Manchukuo, carved out from Chinese Manchuria.\nHe made the de-facto colony economically dependant on Japan, and in its strive to rapidly industrialize the region in a Soviet-style Five Year Plan 40\% of the four million Chinese put to forced labor died.""") justify True
    text _("""He would then occupy a number of posts in war-time cabinets, up to and including as Minister of Commerce and Industry under Hideki Tojo, becoming one of the co-signers of the 1941 declaration of war on the United States. In 1945, after the surrender of Imperial Japan, he was arrested to be tried as a war criminal of Type A for 'crimes against peace'.""") justify True
    text _("""His war crime trial, however, never happened. The ignition of the Cold War between the USSR and the United States of America lead the occupational government under Douglas McArtur to pursue a 'Reverse Course' on many of the policies they had implemented that far, in an effort to contrast the rise of the Japanese Socialist Party.\nKishi was released from prison in 1948 and, with the end of occupation, the clause of the peace treaty which prohibited war-time government members to run for office was rescinded. He got elected to the Japanese National Diet as a Liberal in 1953.""") justify True
    text _("""Following his appointment as leader of the newly formed Liberal Democratic Party, his tenure as Prime Minister was characterized by efforts to use the power of the government to diminish the power of unions and left-leaning parties, and an outspoken attempt at reforming Article 9 of the Japanese Constitution, which to this day 'outlaws war as a means to settle international disputes involving the state' and thus prevented it from fully rearming.\nHis fatal misstep came in 1960 when his underhanded efforts to pass a controversial reform to the US-Japan Security treaty before a visit from then US President Dwight D. Eisenhower, although successful, kickstarted the Anpo Protests. Disgraced, extremely unpopular and bereft of allies even in his own party, was forced to {a=https://www.youtube.com/watch?v=2zlmP3v_h88|resign in disgrace in favour of Hayato Ikeda, who would take the LDP policies in a very different direction. He would, in the interim, survive a stabbing attack from a right-wing ultranationalist{/a}.""") justify True
    text _("""Also of Note:\n - Nobusuke Kishi is the maternal grandfather of Abe Shinzo, the longest serving Prime Minister in the History of Japan.""")