screen scr_chateau_dubois():
    label _("Chateau de Bois-le-Dumont")
    add "images/cdx/locs/001_chateau_du_bois.png"
    text _("""One of the most renown among France's 45.000 châteaux, the history of this estate is as fragmented as its current configuration is bizarre. It started as a vanity project from a member of pre-revolutionary aristocracy, in a bid to emulate the pomp of King Louis the XIV's Palace of Versailles. Unfortunately, the French Revolution would put an end to the project and the September Massacres would put an end to his lineage.""") justify True

    text _("""The never completed project was left to rot for more than a century, becoming the center of numerous urban legends and fanciful stories, like being a hideout for the resistance during World War II. It was eventually acquired by the eccentric Abelard Du Bois in the mid 1950s, who would over the course of two decades turn it into the château as it is today. A lover of history and foreign architecture, he turned each building of the estate into a showcase for one of his passions.""") justify True

    text _("""Nowadays, the château is mainly used as a museum for the various collections Du Bois accumulated over his lifetime, and a popular place to host events and receptions. Some areas, though, remain off limits to the public to this day.""") justify True
    if c_chateau_dubois_config:
        text _("""While the claim to fame of the château are the various buildings, each with their own peculiarities and architectural influences, any conoisseur would be remiss without mentioning the Great Courtyard, the expansion of which was a pet project of Abelard's daughter, Amandine. Styled after the Royal Gardens of Belgium, what it lacks in size the courtyard makes up for in features: from its scattered sculptures to its greenhouse to its variegated offering of flora, no stay at the château is complete without a stroll in this verdant wonderland.""") justify True
    if c_chateau_dubois_taisho:
        text _("""One of the most unique buildings in the château, and really in the country itself, it's the Taisho Building, so named for its architecture and furnishing being inspired by the Taisho period of Japanese history.""") justify True